---
title: "Figure5"
author: "Loecher"
date: "2023-07-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(reticulate)
library(tidyr)

source("figure_utils.R")
save2pdf= TRUE
if (!dir.exists("Fig5")) dir.create("Fig5")
```


## Optimal mtry

```{r}
opt_lambda_opt_mtry = list_from_pdDict_tocsv("data/opt_lambda_opt_mtry/", head=T, verbose=0)
```



```{r}
#for (i in 1:3) diff_bag_rf[[i]]$method = gsub("Diff_bag_vs_rf_", "", diff_bag_rf[[i]]$method)

opt_lambda_opt_mtry[[1]]$method="Linear Model"
opt_lambda_opt_mtry[[1]]$n=50
opt_lambda_opt_mtry[[2]]$method="Linear Model"
opt_lambda_opt_mtry[[2]]$n=500
opt_lambda_opt_mtry[[3]]$method="MARS Model"
opt_lambda_opt_mtry[[3]]$n=50
opt_lambda_opt_mtry[[4]]$method="MARS Model"
opt_lambda_opt_mtry[[4]]$n=500


data_list = do.call("rbind.data.frame", opt_lambda_opt_mtry)

```

```{r}
#colnames(data_list)[1:2] = c("none", "optimal")
#dat = pivot_longer(data_list, 1:2, names_to = "shrinkage", values_to = "bagminusrf")
dat_opt = data_list
dat_opt$n = as.character(dat_opt$n)

gp_opt = ggplot(dat_opt,aes(x=snr,y=lambda,color=n))+geom_line(lwd=1)+ 
    geom_point(aes(shape = n), size =1 )+ 
    facet_wrap(~ method, scales = "free") + 
    ylab("Optimal lambda")+ xlab("signal-to-noise ratio") + 
    geom_abline(intercept = 0, slope = 0, linewidth = 0.75,linetype="dotted")+
    theme_bw() + scale_x_log10()
gp_opt
```

```{r, eval = save2pdf}
ggsave("Fig5/Lambda_vs_SNR_optimal_mtry.pdf",gp_opt, width = 8, height = 4)
```

## Default mtry

```{r}
opt_lambda_default_mtry = list_from_pdDict_tocsv("data/opt_lambda_default_mtry/", head=TRUE, verbose=0)
```



```{r}
#for (i in 1:3) diff_bag_rf[[i]]$method = gsub("Diff_bag_vs_rf_", "", diff_bag_rf[[i]]$method)

opt_lambda_default_mtry[[1]]$method="Linear Model"
opt_lambda_default_mtry[[1]]$n=50
opt_lambda_default_mtry[[2]]$method="Linear Model"
opt_lambda_default_mtry[[2]]$n=500
opt_lambda_default_mtry[[3]]$method="MARS Model"
opt_lambda_default_mtry[[3]]$n=50
opt_lambda_default_mtry[[4]]$method="MARS Model"
opt_lambda_default_mtry[[4]]$n=500


data_list = do.call("rbind.data.frame", opt_lambda_default_mtry)

```

```{r}
#colnames(data_list)[1:2] = c("none", "optimal")
#dat = pivot_longer(data_list, 1:2, names_to = "shrinkage", values_to = "bagminusrf")
dat_default = data_list
dat_default$n = as.character(dat_default$n)

gp_default = ggplot(dat_default,aes(x=snr,y=lambda,color=n))+geom_line(lwd=1)+ 
    geom_point(aes(shape = n), size =1 )+ 
    facet_wrap(~ method, scales = "free") + 
    ylab("Optimal lambda")+ xlab("signal-to-noise ratio") + 
    geom_abline(intercept = 0, slope = 0, linewidth = 0.75,linetype="dotted")+
    theme_bw() + scale_x_log10()
gp_default
```

```{r, eval = save2pdf}
ggsave("Fig5/Lambda_vs_SNR_default_mtry.pdf",gp_default, width = 8, height = 4)
```



## Combining both figures into one:

```{r}
dat_opt$mtry="optimal"
dat_default$mtry="default"
dat_all = rbind.data.frame(dat_opt, dat_default)
dat_all$n = as.character(dat_all$n)
```

```{r}

gp_all = ggplot(dat_all,aes(x=snr,y=lambda,color=n, linetype = mtry))+geom_line(lwd=1)+ 
    geom_point(aes(shape = n), size =1 )+ 
    facet_wrap(~ method, scales = "free") + 
    ylab("Optimal lambda")+ xlab("signal-to-noise ratio") + 
    geom_abline(intercept = 0, slope = 0, linewidth = 0.75, linetype="dotted")+
    theme_bw() + scale_x_log10() + scale_y_sqrt()
gp_all
```

```{r, eval = save2pdf}
ggsave("Fig5/Lambda_vs_SNR.pdf",gp_all, width = 8, height = 4)
```

## Arranging both figures on one grid:

```{r}
#lame:
#gp_grid = ggpubr::ggarrange(gp_default,gp_opt,nrow=2)
dat_opt$mtry="optimal mtry"
dat_default$mtry="default mtry"
dat_all = rbind.data.frame(dat_opt, dat_default)
dat_all$n = as.character(dat_all$n)
gp_grid = ggplot(dat_all,aes(x=snr,y=lambda,color=n))+geom_line(lwd=1)+ 
    geom_point(aes(shape = n), size =1 )+ 
    facet_wrap(~ method + mtry, scales = "free") + 
    ylab("Optimal lambda")+ xlab("signal-to-noise ratio") + 
    geom_abline(intercept = 0, slope = 0, linewidth = 0.75, linetype="dotted")+
    theme_bw() + scale_x_log10() #+ scale_y_sqrt()
gp_grid
```


```{r, eval = save2pdf}
ggsave("Fig5/Lambda_vs_SNR_grid.pdf",gp_grid, width = 8, height = 5)
```